"""
Training data for the intent classifier.

All labeled examples live here.
Edit this file to teach the agent new patterns — no code logic to touch.
Each entry is (example_phrase, intent_label).

Intent labels: "weather" | "calculator" | "time" | "notes" | "other"
"""

TRAINING_DATA: list[tuple[str, str]] = [

    # ── weather: explicit phrases ──────────────────────────────────────────
    ("weather in london",                   "weather"),
    ("give me weather of london",           "weather"),
    ("weather of paris",                    "weather"),
    ("what is the weather in new york",     "weather"),
    ("weather in mumbai",                   "weather"),
    ("show weather for delhi",              "weather"),
    ("forecast for tokyo",                  "weather"),
    ("temperature in berlin",               "weather"),
    ("how is weather in sydney",            "weather"),
    ("weather today in chicago",            "weather"),
    ("what is the temperature in dubai",    "weather"),
    ("tell me the weather in rome",         "weather"),
    ("weather report for toronto",          "weather"),
    ("is it raining in amsterdam",          "weather"),
    ("how hot is it in cairo",              "weather"),
    ("what is the climate in moscow",       "weather"),
    ("how cold is oslo",                    "weather"),
    ("weather for los angeles",             "weather"),

    # ── weather: bare city / place names ──────────────────────────────────
    ("london",          "weather"),
    ("paris",           "weather"),
    ("new york",        "weather"),
    ("tokyo",           "weather"),
    ("mumbai",          "weather"),
    ("delhi",           "weather"),
    ("berlin",          "weather"),
    ("sydney",          "weather"),
    ("chicago",         "weather"),
    ("dubai",           "weather"),
    ("rome",            "weather"),
    ("toronto",         "weather"),
    ("amsterdam",       "weather"),
    ("bangalore",       "weather"),
    ("los angeles",     "weather"),
    ("san francisco",   "weather"),
    ("mexico city",     "weather"),
    ("rio de janeiro",  "weather"),
    ("cairo",           "weather"),
    ("moscow",          "weather"),
    ("oslo",            "weather"),
    ("seoul",           "weather"),
    ("beijing",         "weather"),
    ("istanbul",        "weather"),
    ("jaipur",          "weather"),
    ("hyderabad",       "weather"),
    ("kolkata",         "weather"),
    ("chennai",         "weather"),
    ("pune",            "weather"),
    ("lahore",          "weather"),
    ("karachi",         "weather"),
    ("dhaka",           "weather"),
    ("kathmandu",       "weather"),
    ("colombo",         "weather"),

    # ── calculator: expressions ───────────────────────────────────────────
    ("5+2",             "calculator"),
    ("5 + 2",           "calculator"),
    ("3*4",             "calculator"),
    ("10-3",            "calculator"),
    ("4*5",             "calculator"),
    ("100-50",          "calculator"),
    ("6 + 7",           "calculator"),
    ("20 - 5",          "calculator"),
    ("3 * 3",           "calculator"),
    ("8 * 9",           "calculator"),
    ("100 + 200",       "calculator"),
    ("50 - 25",         "calculator"),

    # ── calculator: natural language ──────────────────────────────────────
    ("give me answer for 5+2",      "calculator"),
    ("gimme answer for 3*4",        "calculator"),
    ("calculate 10-3",              "calculator"),
    ("what is 4*5",                 "calculator"),
    ("compute 100-50",              "calculator"),
    ("what is 6 + 7",               "calculator"),
    ("solve 100 + 200",             "calculator"),
    ("50 - 25 equals what",         "calculator"),
    ("add 5 and 3",                 "calculator"),
    ("multiply 4 by 5",             "calculator"),
    ("subtract 10 from 20",         "calculator"),
    ("what is 8 * 9",               "calculator"),
    ("plus 3 and 7",                "calculator"),
    ("times 6 and 9",               "calculator"),
    ("minus 4 from 10",             "calculator"),

    # ── time / date: explicit ─────────────────────────────────────────────
    ("what time is it",             "time"),
    ("current time",                "time"),
    ("time in tokyo",               "time"),
    ("time in new york",            "time"),
    ("time in london",              "time"),
    ("what time is it in dubai",    "time"),
    ("clock in mumbai",             "time"),
    ("what is the time in paris",   "time"),
    ("time right now",              "time"),
    ("local time",                  "time"),

    # ── time / date: date queries ─────────────────────────────────────────
    ("what day is today",           "time"),
    ("what is today date",          "time"),
    ("today date",                  "time"),
    ("what is the date today",      "time"),
    ("what day is it",              "time"),
    ("today's date",                "time"),
    ("current date",                "time"),
    ("what month is it",            "time"),
    ("tell me the date",            "time"),

    # ── time / date: date math ────────────────────────────────────────────
    ("add 3 days to today",         "time"),
    ("3 days from now",             "time"),
    ("5 days from today",           "time"),
    ("what day is 7 days from now", "time"),
    ("2 days ago",                  "time"),
    ("10 days later",               "time"),
    ("add 1 day to today",          "time"),

    # ── notes: save ───────────────────────────────────────────────────────
    ("note: buy milk",                  "notes"),
    ("remind me to call mom",           "notes"),
    ("remember to pay rent",            "notes"),
    ("save a note: dentist appointment","notes"),
    ("add note: finish report",         "notes"),
    ("don't forget to water plants",    "notes"),
    ("write down: pick up keys",        "notes"),
    ("jot down: meeting at 3pm",        "notes"),
    ("keep a note: grocery list",       "notes"),
    ("memo: call the plumber",          "notes"),
    ("remind me buy groceries",         "notes"),
    ("save this: team lunch tomorrow",  "notes"),

    # ── notes: view ───────────────────────────────────────────────────────
    ("show notes",          "notes"),
    ("view notes",          "notes"),
    ("list notes",          "notes"),
    ("my notes",            "notes"),
    ("show my notes",       "notes"),
    ("what are my notes",   "notes"),
    ("see notes",           "notes"),
    ("display notes",       "notes"),
    ("tell me my notes",    "notes"),
    ("get notes",           "notes"),
    ("read notes",          "notes"),
    ("notes",               "notes"),

    # ── notes: delete ─────────────────────────────────────────────────────
    ("delete note 1",       "notes"),
    ("remove note 2",       "notes"),
    ("delete note 3",       "notes"),
    ("erase note 1",        "notes"),
    ("clear all notes",     "notes"),

    # ── other / greeting ──────────────────────────────────────────────────
    ("hello",           "other"),
    ("hi",              "other"),
    ("hey there",       "other"),
    ("how are you",     "other"),
    ("what can you do", "other"),
    ("help",            "other"),
    ("who are you",     "other"),
    ("what are you",    "other"),
    ("good morning",    "other"),
    ("thanks",          "other"),
    ("thank you",       "other"),
]
